#!/usr/bin/env python3
"""Plot Digifiz oscilloscope dump generated by /oscilloscope_dump endpoint."""

import argparse
import struct
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

HEADER_FMT = "<7I"
HEADER_SIZE = struct.calcsize(HEADER_FMT)
MAGIC = 0x43534F44


def unpack_bits(words: np.ndarray, sample_count: int) -> np.ndarray:
    bits = np.zeros(sample_count, dtype=np.uint8)
    for idx in range(sample_count):
        word = words[idx // 32]
        bits[idx] = (word >> (idx % 32)) & 1
    return bits


def main() -> None:
    parser = argparse.ArgumentParser(description="Visualize Digifiz oscilloscope dump")
    parser.add_argument("dump", type=Path, help="Path to oscilloscope_dump.bin")
    parser.add_argument("--output", type=Path, help="Save plot to file instead of showing")
    args = parser.parse_args()

    payload = args.dump.read_bytes()
    if len(payload) < HEADER_SIZE:
        raise ValueError("File too small to contain a valid header")

    magic, version, sample_rate_hz, sample_count, packed_words, write_index, wrapped = struct.unpack_from(HEADER_FMT, payload, 0)
    if magic != MAGIC:
        raise ValueError(f"Unexpected magic: 0x{magic:08X}")
    if version != 1:
        raise ValueError(f"Unsupported version: {version}")

    expected_size = HEADER_SIZE + packed_words * 4 * 2
    if len(payload) != expected_size:
        raise ValueError(f"Unexpected payload size: got {len(payload)}, expected {expected_size}")

    offset = HEADER_SIZE
    rpm_words = np.frombuffer(payload, dtype=np.uint32, count=packed_words, offset=offset)
    speed_words = np.frombuffer(payload, dtype=np.uint32, count=packed_words, offset=offset + packed_words * 4)

    rpm = unpack_bits(rpm_words, sample_count)
    speed = unpack_bits(speed_words, sample_count)

    if wrapped:
        rpm = np.concatenate((rpm[write_index:], rpm[:write_index]))
        speed = np.concatenate((speed[write_index:], speed[:write_index]))

    time_axis = np.arange(sample_count) / sample_rate_hz

    plt.figure(figsize=(12, 4))
    plt.step(time_axis, rpm + 1.2, where="post", label="RPM input (GPIO35)")
    plt.step(time_axis, speed, where="post", label="Speed input (GPIO39)")
    # Sample dots (overlay)
    plt.plot(time_axis, rpm + 1.2, marker='o', linestyle='None')
    plt.plot(time_axis, speed, marker='o', linestyle='None')

    plt.yticks([0, 1.2], ["Speed", "RPM"])
    plt.xlabel("Time, s")
    plt.ylabel("Digital level")
    plt.title("Digifiz oscilloscope capture")
    plt.grid(True, alpha=0.3)
    plt.legend(loc="upper right")
    plt.tight_layout()

    if args.output:
        plt.savefig(args.output, dpi=150)
    else:
        plt.show()


if __name__ == "__main__":
    main()
