#!/usr/bin/env python3
"""Plot Digifiz oscilloscope dump generated by /oscilloscope_dump endpoint.

Adds 4 RPM algorithms:
  1) FFT peak (already existed)
  2) LEGACY (C port): debounce + average every 8 periods + median filter
  3) STABLE  (C port): debounce + direct period-to-Hz
  4) GLITCH  (C port): debounce + min low/high pulse width gating + direct period-to-Hz

Notes:
- The C tacho algorithms compute **Hz** as: Hz = 1_000_000 / period_us
- Calibration kept as before: RPM = Hz * 30
"""

import argparse
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

import matplotlib.pyplot as plt
import numpy as np

# =========================
# Parameters (moved to top)
# =========================
RPM_DEBOUNCE_TICKS_US = 100        # digifiz_parameters.rpm_debounce_ticks.value
RPM_MIN_HIGH_US = 300             # digifiz_parameters.rpm_min_high_us.value
RPM_MIN_LOW_US = 300              # digifiz_parameters.rpm_min_low_us.value
RPM_SANITY_CHECK_HZ = 1200        # digifiz_parameters.rpm_sanity_check.value (C compares Hz)

LEGACY_AVG_SHIFT = 3              # (rpm_cnt & 0x07) == 0 -> average over 8 samples
LEGACY_AVG_N = 1 << LEGACY_AVG_SHIFT

# NOTE: RPM_WINDOW_SIZE is defined elsewhere in your firmware (tacho.h).
# Pick the same value here to match behavior. If unsure, set it to whatever your build uses.
RPM_WINDOW_SIZE = 9               # median filter window size for LEGACY algo


HEADER_FMT = "<7I"
HEADER_SIZE = struct.calcsize(HEADER_FMT)
MAGIC = 0x43534F44


def unpack_bits(words: np.ndarray, sample_count: int) -> np.ndarray:
    bits = np.zeros(sample_count, dtype=np.uint8)
    for idx in range(sample_count):
        word = words[idx // 32]
        bits[idx] = (word >> (idx % 32)) & 1
    return bits


def dominant_freq_hz(x_bits: np.ndarray, fs_hz: float) -> float:
    """
    Estimate dominant (baseline) frequency in Hz using FFT peak (excluding DC).
    Uses Hann window + optional parabolic peak interpolation.
    """
    x = x_bits.astype(np.float64)

    # Remove DC offset (important for 0/1 digital signal)
    x = x - np.mean(x)

    n = x.size
    if n < 8:
        return 0.0

    # Window to reduce leakage
    w = np.hanning(n)
    xw = x * w

    # FFT
    spec = np.fft.rfft(xw)
    mag = np.abs(spec)

    # Ignore DC bin
    if mag.size <= 2:
        return 0.0
    mag[0] = 0.0

    k = int(np.argmax(mag))
    if k <= 0 or k >= mag.size - 1:
        # Edge bin, can't interpolate
        return k * fs_hz / n

    # Parabolic interpolation around peak for sub-bin estimate
    a, b, c = mag[k - 1], mag[k], mag[k + 1]
    denom = (a - 2.0 * b + c)
    if denom == 0:
        delta = 0.0
    else:
        delta = 0.5 * (a - c) / denom  # in bins

    k_interp = k + delta
    return float(k_interp * fs_hz / n)


def _to_us(sample_idx: int, fs_hz: float) -> int:
    # mimic 1 MHz timer ticks as close as possible
    return int(round(sample_idx * (1_000_000.0 / fs_hz)))


def _extract_edges(bits: np.ndarray) -> List[tuple[int, int]]:
    """
    Return list of (idx, level) for each edge, where level is the new level after transition.
    Rising: level=1, Falling: level=0.
    """
    if bits.size < 2:
        return []
    prev = int(bits[0])
    edges: List[tuple[int, int]] = []
    for i in range(1, bits.size):
        cur = int(bits[i])
        if cur != prev:
            edges.append((i, cur))
            prev = cur
    return edges


@dataclass
class _MedianFilter:
    data: List[int]
    index: int = 0

    @classmethod
    def create(cls, size: int) -> "_MedianFilter":
        return cls(data=[0] * size, index=0)

    def insert(self, value: int) -> None:
        self.data[self.index] = int(value)
        self.index = (self.index + 1) % len(self.data)

    def median(self) -> int:
        # insertion-sort copy (same idea as C)
        arr = self.data[:]
        for i in range(1, len(arr)):
            key = arr[i]
            j = i - 1
            while j >= 0 and arr[j] > key:
                arr[j + 1] = arr[j]
                j -= 1
            arr[j + 1] = key
        return arr[len(arr) // 2]

    def update(self, new_value: int) -> int:
        self.insert(new_value)
        return self.median()


def rpm_hz_algo_stable(rpm_bits: np.ndarray, fs_hz: float) -> float:
    """
    Port of gpio_isr_handler_stable + frequency_task_stable.
    Returns last accepted Hz within the capture.
    """
    last_time_falling = 0
    last_time_valid_rising = 0

    last_hz: float = 0.0

    for idx, new_level in _extract_edges(rpm_bits):
        t_us = _to_us(idx, fs_hz)

        if new_level == 1:
            # Rising
            if last_time_falling != 0 and (t_us - last_time_falling) < RPM_DEBOUNCE_TICKS_US:
                continue

            if last_time_valid_rising != 0:
                interval_us = t_us - last_time_valid_rising
                if interval_us >= RPM_DEBOUNCE_TICKS_US and interval_us > 0:
                    hz = 1_000_000.0 / float(interval_us)
                    if hz < float(RPM_SANITY_CHECK_HZ):
                        last_hz = hz

            last_time_valid_rising = t_us
        else:
            # Falling
            last_time_falling = t_us

    return float(last_hz)


def rpm_hz_algo_glitch(rpm_bits: np.ndarray, fs_hz: float) -> float:
    """
    Port of gpio_isr_handler_glitch + frequency_task_glitch.
    Returns last accepted Hz within the capture.
    """
    last_time_rising = 0
    last_time_falling = 0
    last_time_valid_rising = 0

    last_hz: float = 0.0

    for idx, new_level in _extract_edges(rpm_bits):
        t_us = _to_us(idx, fs_hz)

        if new_level == 1:
            # Rising
            if last_time_falling != 0 and (t_us - last_time_falling) < RPM_DEBOUNCE_TICKS_US:
                continue

            if last_time_falling != 0:
                low_us = t_us - last_time_falling
                if low_us < RPM_MIN_LOW_US:
                    continue

            last_time_rising = t_us

        else:
            # Falling
            last_time_falling = t_us

            if last_time_rising == 0:
                continue

            high_us = t_us - last_time_rising
            if high_us < RPM_MIN_HIGH_US:
                continue

            if last_time_valid_rising != 0:
                period_us = last_time_rising - last_time_valid_rising
                if period_us >= RPM_DEBOUNCE_TICKS_US and period_us > 0:
                    hz = 1_000_000.0 / float(period_us)
                    if hz < float(RPM_SANITY_CHECK_HZ):
                        last_hz = hz

            last_time_valid_rising = last_time_rising

    return float(last_hz)


def rpm_hz_algo_legacy(rpm_bits: np.ndarray, fs_hz: float) -> float:
    """
    Port of gpio_isr_handler_legacy + frequency_task_legacy:
      - debounce on rising
      - compute interval between valid risings
      - accumulate 8 intervals, send avg interval
      - convert to Hz and apply median filter window
    Returns last accepted Hz (median-filtered) within the capture.
    """
    last_time_falling = 0
    last_time_valid_rising = 0

    average_intv_q = 0
    rpm_cnt = 0

    mf = _MedianFilter.create(RPM_WINDOW_SIZE)
    last_hz: float = 0.0

    for idx, new_level in _extract_edges(rpm_bits):
        t_us = _to_us(idx, fs_hz)

        if new_level == 1:
            # Rising
            if last_time_falling != 0 and (t_us - last_time_falling) < RPM_DEBOUNCE_TICKS_US:
                continue

            if last_time_valid_rising != 0:
                interval_us = t_us - last_time_valid_rising
                if interval_us >= RPM_DEBOUNCE_TICKS_US and interval_us > 0:
                    average_intv_q += int(interval_us)
                    rpm_cnt += 1

                    if (rpm_cnt & (LEGACY_AVG_N - 1)) == 0:
                        avg_intv_us = average_intv_q >> LEGACY_AVG_SHIFT
                        average_intv_q = 0

                        hz_raw = 1_000_000.0 / float(avg_intv_us) if avg_intv_us > 0 else 0.0
                        hz_med = mf.update(int(hz_raw))  # C uses integer math
                        if hz_med < RPM_SANITY_CHECK_HZ:
                            last_hz = float(hz_med)

            last_time_valid_rising = t_us
        else:
            # Falling
            last_time_falling = t_us

    return float(last_hz)


def main() -> None:
    parser = argparse.ArgumentParser(description="Visualize Digifiz oscilloscope dump")
    parser.add_argument("dump", type=Path, help="Path to oscilloscope_dump.bin")
    parser.add_argument("--output", type=Path, help="Save plot to file instead of showing")
    args = parser.parse_args()

    payload = args.dump.read_bytes()
    if len(payload) < HEADER_SIZE:
        raise ValueError("File too small to contain a valid header")

    magic, version, sample_rate_hz, sample_count, packed_words, write_index, wrapped = struct.unpack_from(
        HEADER_FMT, payload, 0
    )
    if magic != MAGIC:
        raise ValueError(f"Unexpected magic: 0x{magic:08X}")
    if version != 1:
        raise ValueError(f"Unsupported version: {version}")

    expected_size = HEADER_SIZE + packed_words * 4 * 2
    if len(payload) != expected_size:
        raise ValueError(f"Unexpected payload size: got {len(payload)}, expected {expected_size}")

    offset = HEADER_SIZE
    rpm_words = np.frombuffer(payload, dtype=np.uint32, count=packed_words, offset=offset)
    speed_words = np.frombuffer(payload, dtype=np.uint32, count=packed_words, offset=offset + packed_words * 4)

    rpm = unpack_bits(rpm_words, sample_count)
    speed = unpack_bits(speed_words, sample_count)

    if wrapped:
        rpm = np.concatenate((rpm[write_index:], rpm[:write_index]))
        speed = np.concatenate((speed[write_index:], speed[:write_index]))

    fs = float(sample_rate_hz)

    # -------------------------
    # RPM: 4 different algorithms
    # -------------------------
    rpm_hz_fft = dominant_freq_hz(rpm, fs)
    rpm_hz_stable = rpm_hz_algo_stable(rpm, fs)
    rpm_hz_legacy = rpm_hz_algo_legacy(rpm, fs)
    rpm_hz_glitch = rpm_hz_algo_glitch(rpm, fs)

    # Speed stays FFT-based as before
    speed_hz_fft = dominant_freq_hz(speed, fs)

    # --- Calibration ---
    rpm_fft = rpm_hz_fft * 30.0
    rpm_stable = rpm_hz_stable * 30.0
    rpm_legacy = rpm_hz_legacy * 30.0
    rpm_glitch = rpm_hz_glitch * 30.0

    speed_value = speed_hz_fft * 0.97

    # Console preview
    print(f"RPM FFT    : {rpm_hz_fft:.3f} Hz -> {rpm_fft:.1f} RPM")
    print(f"RPM STABLE : {rpm_hz_stable:.3f} Hz -> {rpm_stable:.1f} RPM")
    print(f"RPM LEGACY : {rpm_hz_legacy:.3f} Hz -> {rpm_legacy:.1f} RPM")
    print(f"RPM GLITCH : {rpm_hz_glitch:.3f} Hz -> {rpm_glitch:.1f} RPM")
    print(f"Speed FFT  : {speed_hz_fft:.3f} Hz -> {speed_value:.2f}")

    time_axis = np.arange(sample_count) / sample_rate_hz

    fig, ax = plt.subplots(figsize=(12, 4))
    ax.step(time_axis, rpm + 1.2, where="post", label="RPM input (GPIO35)")
    ax.step(time_axis, speed, where="post", label="Speed input (GPIO39)")

    ax.set_yticks([0, 1.2], ["Speed", "RPM"])
    ax.set_xlabel("Time, s")
    ax.set_ylabel("Digital level")
    ax.set_title("Digifiz oscilloscope capture")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="upper right")

    # Draw text on plot
    info = (
        "RPM (4 algos):\n"
        f"  FFT    : {rpm_fft:.1f}  ({rpm_hz_fft:.3f} Hz)\n"
        f"  STABLE : {rpm_stable:.1f}  ({rpm_hz_stable:.3f} Hz)\n"
        f"  LEGACY : {rpm_legacy:.1f}  ({rpm_hz_legacy:.3f} Hz)\n"
        f"  GLITCH : {rpm_glitch:.1f}  ({rpm_hz_glitch:.3f} Hz)\n"
        f"Speed (FFT): {speed_value:.2f}  ({speed_hz_fft:.3f} Hz)"
    )
    ax.text(
        0.01,
        0.98,
        info,
        transform=ax.transAxes,
        va="top",
        ha="left",
        bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8),
    )

    fig.tight_layout()

    if args.output:
        fig.savefig(args.output, dpi=150)
    else:
        plt.show()


if __name__ == "__main__":
    main()