#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <RTClib.h>
#include <Wire.h>
#include "Arduino.h"
#include "eeprom.h"


//0..64 normal parameters
//128...128+64 read parameters
//223..225 execute commands

#define PARAMETER_RPMCOEFFICIENT 0
#define PARAMETER_SPEEDCOEEFICIENT 1
#define PARAMETER_COOLANTTHERMISTORB 2
#define PARAMETER_OILTHERMISTORB 3
#define PARAMETER_AIRTHERMISTORB 4
#define PARAMETER_TANKMINRESISTANCE 5
#define PARAMETER_TANKMAXRESISTANCE 6
#define PARAMETER_TAU_COOLANT 7
#define PARAMETER_TAU_OIL 8
#define PARAMETER_TAU_AIR 9
#define PARAMETER_TAU_TANK 10
#define PARAMETER_MILEAGE 11
#define PARAMETER_DAILY_MILEAGE 12
#define PARAMETER_AUTO_BRIGHTNESS 13
#define PARAMETER_BRIGHTNESS_LEVEL 14
#define PARAMETER_TANK_CAPACITY 15
#define PARAMETER_MFA_STATE 16
#define PARAMETER_BUZZER_OFF 17
#define PARAMETER_MAX_RPM 18
#define PARAMETER_BUZZER_OFF 17
#define PARAMETER_READ_ADDITION 128
#define PARAMETER_SET_HOUR 255
#define PARAMETER_SET_MINUTE 254
#define PARAMETER_RESET_DAILY_MILEAGE 253

void initComProtocol();
void changeBLEName();
void protocolParse();
void processData(int par, long value);

#endif
