#ifndef SETUP_H
#define SETUP_H

//#define EMULATE_RTC
//#define DISABLE_EEPROM
#define DISABLE_MANUFACTURER_MFA
#define MANUFACTURER_MFA_SWITCH
#define EMERGENCY_DISABLE_SENSOR_CHECK

#define OIL_RES_10000

//#define YELLOW_GREEN_LED
    
//#define NEW_REVISION

#define GALLONS
#define MILES
#define FAHRENHEIT

#define RPM_8000

#define DIGIFIZ_ORIGINAL_DISPLAY

#endif
