name: Build Digifiz Next
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Replace BUILD_VERSION with tag
      run: |
        TAG_NAME=$(git describe --tags --abbrev=0)
        echo "Using tag: $TAG_NAME"
        sed -i "s/BUILD_VERSION/$TAG_NAME/g" Digifiz/main/data/digifiz_ws_connect.html
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1.1.0
      with:
        esp_idf_version: v5.2.1
        target: esp32s3
        path: 'ESP32/Digifiz/'